### PR TITLE
ACKs

### PR DESCRIPTION
**Pull request by Artaud**
This PR implementes most of what was discussed in https://github.com/dillpixel/fitbit-asap/issues/2.

The basic throughput test passes. We should write some more tests definitely, see https://github.com/dillpixel/fitbit-asap/issues/7.

- the API is kept intact
- messages are sent synchronously - introducing send_next() instead of send_all()
- ACKs are implemented as a boolean on data object
- after sending a message, ASAP waits 5 seconds for an ACK and eventually resends the message. This is handled by a global timer, which is being set and cleared by set_resend_timer() and clear_resend_timer()
- message is dequeued only after successfully receiving an ACK for it
- onmessage is only triggered if we didn't already receive a message with same or higher id
- send_next() can be called multiple times at once, ensures only one message is being sent at once. This is important during startup where we usually send_next() twice at a time.
- message IDs are incremental, starting from a random seed, via get_next_id()

- message expiration is handled via is_message_expired(). Does NOT throw an error on expiration. This is a TODO, I've opened up issue https://github.com/dillpixel/fitbit-asap/issues/8

### CODE REVIEW

**Comment by daveyjones** [comment]
Awesome! I'll review and merge as soon as I get a chance. Thanks!

**Comment by daveyjones** [comment]
Nice job! This is clean and well-written. Merging!

**Comment by Artaud** [comment]
That's great, I'm very glad! Do you plan on bumping the version and putting it up on npm?

**Comment by daveyjones** [comment]
Thanks for the reminder! I published it as version 1.1.0.

**Pull request merged**
